---
- hosts: all
  gather_facts: true
  become: false
  vars:
    NODEJS_VERSION: "v14.19.0"
  tasks:

    - name: Install NVM
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      no_log: True

    - name: Install NodeJs
      ansible.builtin.shell:  |
        . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
        export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
        nvm install {{ NODEJS_VERSION }}

    - name: Install global node packages
      ansible.builtin.shell:  |
        . "{{ ansible_env.HOME }}/.nvm/nvm.sh"
        export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
        "ls {{ ansible_env.HOME }}"
        "{{ ansible_env.HOME }}/.nvm/versions/node/{{NODEJS_VERSION}}/bin/npm install {{item}} -g"
      loop:
        - yarn
        - pm2
